services:
  securecapita:
    container_name: api_consumi_de
    build: .
    image: api_consumi_de
    ports: 
      - 8446:3000
    expose:
      - 8446
    networks:
      - net1

networks:
  net1:
    name: backend_internalnet
    external: true


